[package]
name = "introspect_macros"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
cairo-lang-macro = "0.2.1"
cairo-lang-parser = "2.13.1"
cairo-lang-syntax = "2.13.1"
salsa = "0.24.0"
thiserror.workspace = true
indent = "0.1.1"
indoc = "2.0.7"
