[package]
name = "introspect_macros"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
cairo-lang-macro.workspace = true
cairo-lang-starknet-classes.workspace = true
cairo-syntax-parser.workspace = true
introspect-rust-macros.workspace = true
introspect-types.workspace = true
itertools.workspace = true
salsa = "0.24.0"
starknet-types-core.workspace = true
thiserror.workspace = true
