[package]
name = "introspect_macros"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
cairo-lang-macro.workspace = true
cairo-lang-starknet-classes.workspace = true
cairo-syntax-parser.workspace = true
const_format = "0.2.35"
indent.workspace = true
indoc = "2.0.7"
introspect-rust-macros.workspace = true
introspect-types.workspace = true
itertools.workspace = true
paste = "1.0"
proc-macro2.workspace = true
salsa = "0.24.0"
starknet-types-core.workspace = true
thiserror.workspace = true
