[package]
name = "introspect_types"
version.workspace = true
edition.workspace = true
cairo-version.workspace = true
scarb-version.workspace = true
repository.workspace = true
experimental-features = [
    "associated_item_constraints",
    "negative_impls",
    "user_defined_inline_macros",
]

[dependencies]
starknet.workspace = true
core_ext.workspace = true

[dev-dependencies]
snforge_std.workspace = true
assert_macros.workspace = true
introspect_test_utils.workspace = true

[tool]
fmt.workspace = true
scarb.workspace = true
snforge.workspace = true

[lib]
