[package]
name = "introspect_types"
version.workspace = true
edition.workspace = true
cairo-version.workspace = true
scarb-version.workspace = true
repository.workspace = true
experimental-features = ["associated_item_constraints", "negative_impls"]

[dependencies]
starknet.workspace = true

[dev-dependencies]
snforge_std.workspace = true

[tool]
fmt.workspace = true
scarb.workspace = true

[lib]
