[workspace.package]
version = "0.1.2"
edition = "2024_07"
cairo-version = "2.13.1"
scarb-version = "2.13.1"
repository = "https://github.com/cartridge-gg/introspect"
name = "introspect"

[workspace]
members = [
    "packages/events",
    "packages/types",
    "packages/macros",
    "packages/client",
    "tests/test_contract",
    "tests/events",
    "examples/framework",
    "packages/tests",
]


[workspace.dependencies]
starknet = "2.13.1"
introspect_types = { path = "packages/types" }
introspect_events = { path = "packages/events" }
introspect_macros = { path = "packages/macros" }
introspect_tests = { path = "packages/tests" }
event_tests = { path = "tests/events" }
snforge_std = "0.52.0"
assert_macros = "2.13.1"
cairo_execute = "2.13.1"


[workspace.tool.fmt]
sort-module-level-items = true

[workspace.tool.scarb]
allow-prebuilt-plugins = ["snforge_std"]

[workspace.tool.snforge]

[package]
name = "introspect"
version.workspace = true
edition.workspace = true
cairo-version.workspace = true
scarb-version.workspace = true


[dependencies]
starknet.workspace = true
introspect_types.workspace = true
introspect_events.workspace = true
introspect_macros.workspace = true


[dev-dependencies]
snforge_std.workspace = true
introspect_tests.workspace = true


[lib]

[tool]
fmt.workspace = true
scarb.workspace = true
snforge.workspace = true

[[target.starknet-contract]]
sierra = true
casm = true
