[workspace.package]
version = "0.1.2"
edition = "2024_07"
cairo-version = "2.15.0"
scarb-version = "2.15.0"
repository = "https://github.com/cartridge-gg/introspect"
name = "introspect"

[workspace]
members = [
    # "packages/events",
    "packages/types",
    "packages/macros",
    "packages/macros_tests",
    "packages/testing",
]


[workspace.dependencies]
starknet = "2.15.0"
introspect_types = { path = "packages/types" }
# introspect_events = { path = "packages/events" }
introspect_macros = { path = "packages/macros" }
introspect_test_utils = { path = "packages/testing" }
cgg_utils = { path = "../cairo_core_utils" }
snforge_std = "0.54.0"
assert_macros = "2.15.0"
cairo_execute = "2.15.0"

[workspace.tool.fmt]
sort-module-level-items = true

[workspace.tool.scarb]
allow-prebuilt-plugins = ["snforge_std"]

[workspace.tool.snforge]

[package]
name = "introspect"
version.workspace = true
edition.workspace = true

[dependencies]
starknet.workspace = true
introspect_types.workspace = true
# introspect_events.workspace = true
introspect_macros.workspace = true

[dev-dependencies]
snforge_std.workspace = true

[scripts]
test = "snforge test"

[tool]
fmt.workspace = true
scarb.workspace = true
snforge.workspace = true

[lib]
