[package]
name = "introspect_table"
version.workspace = true
edition.workspace = true
cairo-version.workspace = true
scarb-version.workspace = true
repository.workspace = true
experimental-features = ["associated_item_constraints", "negative_impls"]

[dependencies]
starknet.workspace = true
introspect_types.workspace = true
introspect_events.workspace = true

[dev-dependencies]
snforge_std.workspace = true
assert_macros.workspace = true
introspect_tests.workspace = true

[tool]
fmt.workspace = true
scarb.workspace = true
snforge.workspace = true

[lib]
