[package]
name = "introspect_table_macros"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
cairo-lang-macro.workspace = true
cairo-lang-parser.workspace = true
cairo-lang-syntax.workspace = true
cairo-lang-starknet-classes.workspace = true
salsa = "0.24.0"
thiserror.workspace = true
indent.workspace = true
indoc = "2.0.7"
introspect_macros.workspace = true
introspect-types.workspace = true
introspect-rust-macros.workspace = true
starknet-types-core.workspace = true
itertools.workspace = true
